solution = "tools.sln"
generate = "$(SolutionDir)\\bin\\msvc-debug\\generate-vcxproj.exe $(SolutionDir)"
build = "$(SolutionDir)\\ninja.exe -f msvc.ninja -C $(SolutionDir)"
includes = [
	"xz-embedded/linux/include/linux",
	"xz-embedded/userspace",
	"BearSSL/inc",
	"BearSSL/src",
	".",
]

[[target]]
vs = "Debug"
ninja = "msvc-debug"
default = "msvc-debug"
defines = ["WIN32", "DEBUG", "_DEBUG"]

[[target]]
vs = "Release"
ninja = "msvc-release"
default = "msvc-release"
defines = ["WIN32", "NDEBUG"]

[[project]]
name = "download"
file = "download/download.vcxproj"
target = "bin/{TGT}/download.exe"
dirs = ["download"]

[[project]]
name = "generate-vcxproj"
file = "generate-vcxproj/generate-vcxproj.vcxproj"
target = "bin/{TGT}/generate-vcxproj.exe"
dirs = ["generate-vcxproj"]

[[project]]
name = "tomlc99"
file = "tomlc99.vcxproj"
target = "bin/obj/{TGT}/tomlc99.lib"
dirs = ["tomlc99"]

[[project]]
name = "zlib"
file = "zlib.vcxproj"
target = "bin/obj/{TGT}/zlib.lib"
dirs = ["zlib"]

[[project]]
name = "bearssl"
file = "bearssl.vcxproj"
target = "bin/obj/{TGT}/bearssl.lib"
dirs = [
	"BearSSL/inc",
	"BearSSL/src/aead",
	"BearSSL/src/codec",
	"BearSSL/src/ec",
	"BearSSL/src/hash",
	"BearSSL/src/int",
	"BearSSL/src/mac",
	"BearSSL/src/rand",
	"BearSSL/src/rsa",
	"BearSSL/src/ssl",
	"BearSSL/src/symcipher",
	"BearSSL/src/x509",
	"BearSSL/src",
]

[[project]]
name = "xz"
file = "xz.vcxproj"
target = "bin/obj/{TGT}/xz.lib"
dirs = [
	"xz-embedded/linux/lib/xz",
	"xz-embedded/linux/lib",
	"xz-embedded/linux/include/linux/decompress",
	"xz-embedded/linux/include/linux",
	"xz-embedded/userspace",
]
